// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoH4RDePJc90RUH2VhOZKphMSlRcr3t0g',
    appId: '1:93527628433:web:37b0aaa18c683bf3b77d30',
    messagingSenderId: '93527628433',
    projectId: 'website-task-71a22',
    authDomain: 'website-task-71a22.firebaseapp.com',
    storageBucket: 'website-task-71a22.appspot.com',
    measurementId: 'G-QC504THL0Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDyDekCGjFI08dagC2FnZ61E14BmX6Koo',
    appId: '1:93527628433:android:c2189372eb4b1a37b77d30',
    messagingSenderId: '93527628433',
    projectId: 'website-task-71a22',
    storageBucket: 'website-task-71a22.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAY1nPZ5NRXN7w3CVwsR7UNo5xCK1GPIA',
    appId: '1:93527628433:ios:b421f7320462540db77d30',
    messagingSenderId: '93527628433',
    projectId: 'website-task-71a22',
    storageBucket: 'website-task-71a22.appspot.com',
    iosBundleId: 'com.example.websiteTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAY1nPZ5NRXN7w3CVwsR7UNo5xCK1GPIA',
    appId: '1:93527628433:ios:40249502b441a41db77d30',
    messagingSenderId: '93527628433',
    projectId: 'website-task-71a22',
    storageBucket: 'website-task-71a22.appspot.com',
    iosBundleId: 'com.example.websiteTask.RunnerTests',
  );
}
